import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import { AuthProvider } from "./components/Context/AuthProvider";
const thiccboi = localFont({
  src: './fonts/thiccboi/THICCCBOI-Regular.woff2'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <html lang="en">
      <body
        className={`${thiccboi.className}  antialiased`}
        >

      <AuthProvider >
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
